kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello from the cloud
    when:
      branch:
        - develop

  - name: test
    image: maven:3-openjdk-15-slim
    commands:
      - mvn test
    when:
      branch:
        - consumer
